name: learn-github-actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Branch
        uses: actions/checkout@v1
      # Run a diagnostic
      - name: Diagnostic
        run: docker run --rm -it -v ${GITHUB_WORKSPACE}:/home/pmixer/pmix-standard jjhursey/pmix-standard /bin/bash -c "ls -la /home/pmixer/pmix-standard"
        shell: bash
      # Run the container tester
      - name: Build and Test
        run: docker run --rm -it -v ${GITHUB_WORKSPACE}:/home/pmixer/pmix-standard jjhursey/pmix-standard /bin/bash -c "cp -R /home/pmixer/pmix-standard pmix-build && cd pmix-build && make"
        shell: bash


      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     # https://docs.github.com/en/actions/reference/encrypted-secrets
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
